# PHP Service Configuration
php:
  image:
    repository: php
    tag: 7.4-apache
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  env:
    # 配置 PHP 连接 MySQL 的数据库环境变量
    - name: MYSQL_HOST
      value: mysql
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: mysql-root-password
    - name: REDIS_HOST
      value: redis
    - name: MQ_HOST
      value: mq

# MySQL Service Configuration
mysql:
  image:
    repository: mysql
    tag: 8.0
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    size: 10Gi
  env:
    MYSQL_ROOT_PASSWORD: wsy123456   # 这里可以直接定义密码或使用 secret
  secret:
    name: mysql-secret
    data:
      mysql-root-password: wsy123456  # 建议使用 Kubernetes Secret 加密密码

# Redis Service Configuration
redis:
  image:
    repository: redis
    tag: 6.2
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379

# MQ (e.g., RabbitMQ) Service Configuration
mq:
  image:
    repository: rabbitmq
    tag: 3-management
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5672
  managementPort: 15672  # RabbitMQ 的管理界面端口
  env:
    RABBITMQ_DEFAULT_USER: wsy
    RABBITMQ_DEFAULT_PASS: wsy123456

# Global Configurations
global:
  storageClass: standard  # 配置持久化存储类，如果需要持久化
  namespace: php-mysql-redis-mq-namespace  # 命名空间
